name: 'Upstream Sync And Deploy'

on:
  schedule:
    - cron: "0 21 * * *"
    # UTC 시간으로 오후 9시, 한국 시간으로 매일 오전 6시에 실행

  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: dev
        persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: dev
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: dev
        upstream_sync_repo: codestates-seb/seb45_pre_019
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}

        test_mode: false
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}

    - name: Set new_commits flag
      id: set_new_commits
      run: echo "::set-output name=has_new_commits::${{ steps.sync.outputs.has_new_commits }}"

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2 

      - name: Install dependencies
        run: npm install
        working-directory: ./FE
        
      - name: Build
        run: npm run build 
        working-directory: ./FE
        
      - name: SHOW AWS CLI VERSION
        run: |
          aws --version
          
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://stackoverflow-clone \
            --delete
        working-directory: ./FE
